### PR TITLE
fix(kpi-display): update terminology from "OC" to "LOC" 

### LINKED ISSUE #60: fix(kpi-display): correct terminology from OC to LOC in lead time displays
## Description

The KPI display components use the abbreviation **"OC"** (Órdenes de Cambio) instead of the correct **"LOC"** (Lines of Code) when showing lead time totals. This affects both compact and expanded views of the lead time display, as well as the KPIs card in the task bento form.

## Affected Components

- `apps/app/src/features/common/components/kpi-display/kpi-display.tsx` — compact and expanded `LeadTimeDisplay`
- `apps/app/src/features/task-forms/components/task-bento-form/components/kpis/kpis-card.tsx` — `KpisCard`

## Expected Behavior

All lead time labels should read **LOC** (e.g., `({totalLines} LOC)`) instead of **OC**.

## Additional Context

The Spanish expanded label `({totalLines} líneas OC)` should also be updated to `({totalLines} líneas LOC)`. Both hardcoded label strings are candidates for i18n extraction.

## Linked PR

- #54

### PR DESCRIPTION
**Pull request by odtorres**
replace all OC for LOC

## Summary by CodeRabbit

* **New Features**
  * KPI and lead-time displays now use localized labels for counts and lines, supporting translated strings.
* **Style**
  * Updated unit labels in KPI displays for consistent terminology across compact and expanded views.
* **Documentation**
  * Added new localization entries for English and Spanish to enable translated lead-time labels.

### CODE REVIEW

File: apps/app/src/features/common/components/kpi-display/kpi-display.tsx [hunk 1]
```diff
@@ -149,7 +149,7 @@ export function LeadTimeDisplay({ leadTime, compact }: LeadTimeDisplayProps) {
             Lead Time
           </span>
           <span className="text-xs text-gray-400 dark:text-gray-500">
-            ({totalLines} OC)
+            ({totalLines} LOC)
```
Comment (korutx) [inline apps/app/src/features/common/components/kpi-display/kpi-display.tsx]: @odtorres `({totalLines} LOC)` — please convert this to i18n. Same for `({totalLines} líneas LOC)` Our i18n system supports arguments, so you can interpolate the value directly.

See [tr.service.ts for reference](https://github.com/microboxlabs/modulariot/blob/trunk/apps/app/src/features/i18n/tr.service.ts#L6-L29
) — for example:

```js
// dictionary entry: "loc_count": "({count} LOC)"
tr("loc_count", dictionary, { count: totalLines })
```

File: apps/app/src/features/common/components/kpi-display/kpi-display.tsx [hunk 2]
```diff
@@ -194,7 +194,7 @@ export function LeadTimeDisplay({ leadTime, compact }: LeadTimeDisplayProps) {
             Lead Time
           </span>
           <span className="text-xs text-gray-400 dark:text-gray-500">
-            ({totalLines} líneas OC)
+            ({totalLines} líneas LOC)
```
Comment (korutx) [inline apps/app/src/features/common/components/kpi-display/kpi-display.tsx]: @odtorres same as before

File: apps/app/src/features/task-forms/components/task-bento-form/components/kpis/kpis-card.tsx [hunk 3]
```diff
@@ -120,7 +120,7 @@ export default function KpisCard({ task, dict }: KpisCardProps) {
           Lead Time
         </span>
         <span className="text-xs text-gray-400 dark:text-gray-500">
-          ({totalLines} OC)
+          ({totalLines} LOC)
```
Comment (korutx) [inline apps/app/src/features/task-forms/components/task-bento-form/components/kpis/kpis-card.tsx]: @odtorres same as before

**Review by korutx — CHANGES_REQUESTED** [review]
@odtorres Please address the comments before merging

**Review by korutx — APPROVED** [review]
WIP
